### ISSUE TITLE
map is not responsive

### ISSUE THREAD

**Issue by yicheng-w** [HackNC/fall2017#7]
![issue sizeof](https://user-images.githubusercontent.com/8659998/29745526-fee6ff8a-8a8a-11e7-8415-1ecfc9031150.png)

**Comment by ArmaanSethi** [comment]
I think its good

**Comment by JoshuaJB** [comment]
Could you show how to reproduce the issue? It seems to resize fine for me in Chrome

**Comment by JoshuaJB** [comment]
I'm going to close this unless somebody can reproduce.
